// Glosario financiero colombiano — cada término es una página indexable.
// Agregar un término = agregar un objeto. `post` enlaza al blog relacionado.

export type Term = {
  slug: string;
  term: string;
  def: string; // 2-4 frases, lenguaje claro
  post?: string; // slug de post relacionado en /blog
};

export const terms: Term[] = [
  { slug: "uvt", term: "UVT (Unidad de Valor Tributario)", def: "Unidad de medida que usa la DIAN para expresar topes, sanciones y tarifas tributarias sin tener que actualizar cada norma. Se ajusta cada año con la inflación: en 2026 vale $52.374. Casi todos los topes de impuestos en Colombia (declarar renta, sanciones, exenciones del 4x1000) están definidos en UVT.", post: "quienes-deben-declarar-renta-en-2026" },
  { slug: "smmlv", term: "SMMLV (Salario Mínimo Mensual Legal Vigente)", def: "El sueldo mensual más bajo que se puede pagar legalmente a un trabajador en Colombia: $1.750.905 en 2026. Sirve además como unidad de referencia para multas, topes de créditos, subsidios y primas de seguros.", post: "cuanto-es-el-salario-minimo-2026-en-colombia" },
  { slug: "auxilio-de-transporte", term: "Auxilio de transporte", def: "Pago mensual adicional ($249.095 en 2026) para trabajadores que ganan hasta dos salarios mínimos. Cuenta como base para calcular prima y cesantías, pero no para aportes a salud y pensión.", post: "cuanto-es-el-salario-minimo-2026-en-colombia" },
  { slug: "cesantias", term: "Cesantías", def: "Prestación social equivalente a un salario mensual por cada año trabajado, que el empleador consigna en un fondo antes del 14 de febrero. Funcionan como ahorro para el desempleo y solo se retiran al terminar el contrato o para vivienda y educación.", post: "cesantias-que-son-y-cuando-se-pagan" },
  { slug: "prima-de-servicios", term: "Prima de servicios", def: "Prestación social que equivale a un salario mensual extra por año, pagado en dos cuotas: máximo el 30 de junio y en los primeros 20 días de diciembre. Todo empleado con contrato laboral tiene derecho proporcional al tiempo trabajado.", post: "cuando-pagan-la-prima-y-como-se-calcula" },
  { slug: "cuatro-por-mil", term: "4x1000 (GMF)", def: "Gravamen a los Movimientos Financieros: impuesto del 0,4% que se cobra al retirar o transferir dinero desde cuentas bancarias. Puedes marcar una única cuenta como exenta hasta 350 UVT mensuales de movimientos.", post: "que-es-el-4x1000-y-como-evitarlo" },
  { slug: "cdt", term: "CDT (Certificado de Depósito a Término)", def: "Inversión de renta fija: depositas un monto en una entidad financiera por un plazo pactado (30 a 360+ días) a cambio de una rentabilidad garantizada desde el inicio. Está protegido por el seguro de depósitos de Fogafín hasta $50 millones por entidad.", post: "que-es-un-cdt-y-cuanto-rinde" },
  { slug: "tasa-efectiva-anual", term: "Tasa Efectiva Anual (E.A.)", def: "La rentabilidad o costo real de un producto financiero en un año, incluyendo el efecto de la capitalización de intereses. Es el único número comparable entre entidades: siempre pide la tasa E.A., no la nominal ni la mensual." },
  { slug: "tasa-nominal", term: "Tasa nominal", def: "Tasa expresada sin incluir el efecto de capitalización (por ejemplo, '12% anual mes vencido'). Puede verse menor que la efectiva anual siendo el mismo costo, por eso se presta para confusión en publicidad de créditos." },
  { slug: "dtf", term: "DTF", def: "Tasa promedio de captación de CDTs a 90 días que calculaba el Banco de la República, usada por años como referencia de créditos e inversiones. Está en desuso: fue reemplazada progresivamente por el IBR." },
  { slug: "ibr", term: "IBR (Indicador Bancario de Referencia)", def: "Tasa de interés de referencia del mercado colombiano a corto plazo, que refleja el costo al que los bancos se prestan entre sí. Muchos créditos de tasa variable se pactan como 'IBR + puntos'." },
  { slug: "uvr", term: "UVR (Unidad de Valor Real)", def: "Unidad que se ajusta diariamente con la inflación, usada principalmente en créditos hipotecarios. Una deuda en UVR mantiene su valor real: si la inflación sube, el saldo en pesos también sube.", post: "que-es-la-inflacion-y-como-afecta-tu-plata" },
  { slug: "trm", term: "TRM (Tasa Representativa del Mercado)", def: "El precio oficial del dólar en pesos colombianos, certificado cada día por la Superintendencia Financiera con base en las operaciones del mercado cambiario. Es la referencia para compras internacionales, giros y contabilidad." },
  { slug: "ipc", term: "IPC (Índice de Precios al Consumidor)", def: "Indicador del DANE que mide cuánto sube el costo de una canasta de bienes y servicios representativa del consumo de los hogares. Su variación anual es lo que llamamos inflación, y define aumentos de arriendos, matrículas y salarios.", post: "que-es-la-inflacion-y-como-afecta-tu-plata" },
  { slug: "inflacion", term: "Inflación", def: "Aumento generalizado y sostenido de los precios: con la misma plata compras cada vez menos. Se mide con el IPC y es el enemigo silencioso del ahorro en efectivo — toda inversión debe compararse contra ella.", post: "que-es-la-inflacion-y-como-afecta-tu-plata" },
  { slug: "interes-compuesto", term: "Interés compuesto", def: "Sistema donde los intereses ganados se suman al capital y también generan intereses. Es el motor del crecimiento del ahorro a largo plazo — y de las deudas de tarjeta cuando solo pagas el mínimo.", post: "que-es-el-interes-compuesto-y-como-usarlo-a-tu-favor" },
  { slug: "interes-simple", term: "Interés simple", def: "Sistema donde los intereses se calculan siempre sobre el capital inicial, sin capitalizarse. Es raro en productos financieros reales; la mayoría de créditos e inversiones en Colombia usan interés compuesto." },
  { slug: "tasa-de-usura", term: "Tasa de usura", def: "Tope legal máximo de interés que puede cobrar un prestamista en Colombia, certificado periódicamente por la Superintendencia Financiera. Cobrar por encima es delito — el gota a gota la supera varias veces.", post: "como-salir-de-deudas" },
  { slug: "central-de-riesgo", term: "Central de riesgo", def: "Entidad que registra el comportamiento crediticio de las personas: qué créditos tienen, cómo pagan y qué moras registran. Las principales en Colombia son Datacrédito y TransUnion; los bancos las consultan antes de aprobar cualquier crédito.", post: "como-mejorar-el-puntaje-en-datacredito" },
  { slug: "puntaje-crediticio", term: "Puntaje crediticio (score)", def: "Número que resume tu comportamiento de pago — en Datacrédito va de 150 a 950. Un puntaje alto te da acceso a créditos más baratos; se construye pagando a tiempo y manteniendo un endeudamiento moderado.", post: "como-mejorar-el-puntaje-en-datacredito" },
  { slug: "habeas-data-financiero", term: "Habeas data financiero", def: "Derecho constitucional a conocer, actualizar y corregir tu información en las centrales de riesgo. Consultar tu propio historial es gratuito e ilimitado, y los reclamos por datos erróneos deben responderse en 15 días hábiles.", post: "como-mejorar-el-puntaje-en-datacredito" },
  { slug: "fondo-de-inversion-colectiva", term: "Fondo de Inversión Colectiva (FIC)", def: "Vehículo donde muchos inversionistas aportan a una bolsa común que un administrador profesional invierte en diversos activos. Permite invertir desde montos bajos con diversificación y liquidez, a cambio de una comisión.", post: "como-empezar-a-invertir-en-colombia-con-poca-plata" },
  { slug: "fogafin", term: "Fogafín", def: "Fondo de Garantías de Instituciones Financieras: asegura los depósitos (cuentas, CDTs) en bancos vigilados hasta $50 millones por persona y por entidad. Si el banco quiebra, Fogafín te devuelve tu plata hasta ese tope.", post: "que-es-un-cdt-y-cuanto-rinde" },
  { slug: "superintendencia-financiera", term: "Superintendencia Financiera", def: "Autoridad que vigila y regula a bancos, aseguradoras, fondos y comisionistas en Colombia. Antes de invertir o pedir crédito con cualquier entidad, verifica que aparezca en su registro de vigiladas — es el filtro básico contra estafas." },
  { slug: "leasing", term: "Leasing", def: "Contrato de arrendamiento financiero: la entidad compra el bien (vivienda, vehículo, maquinaria) y te lo arrienda con opción de compra al final. Común en vivienda por sus ventajas tributarias y menor cuota inicial." },
  { slug: "libranza", term: "Crédito de libranza", def: "Préstamo cuya cuota se descuenta directamente de la nómina o pensión. Por el bajo riesgo de impago suele tener mejores tasas que el crédito de libre inversión, pero compromete tu ingreso antes de que llegue a tu bolsillo." },
  { slug: "compra-de-cartera", term: "Compra de cartera", def: "Operación donde un banco paga tus deudas en otras entidades y las unifica a una tasa menor. Es una de las herramientas más efectivas para bajar el costo de deudas de tarjeta de crédito.", post: "como-salir-de-deudas" },
  { slug: "avance-de-tarjeta", term: "Avance en efectivo", def: "Retiro de dinero en efectivo con cargo a la tarjeta de crédito. Cobra intereses desde el día uno (sin periodo de gracia), a la tasa máxima y con comisión adicional: una de las formas más caras de conseguir liquidez.", post: "como-usar-la-tarjeta-de-credito-sin-endeudarte" },
  { slug: "cuota-de-manejo", term: "Cuota de manejo", def: "Cobro periódico de algunos bancos por 'administrar' tu tarjeta o cuenta. Es negociable y evitable: varias entidades ofrecen productos sin cuota de manejo de por vida.", post: "como-usar-la-tarjeta-de-credito-sin-endeudarte" },
  { slug: "gota-a-gota", term: "Gota a gota (paga diario)", def: "Préstamo informal ilegal con tasas que superan el 400% anual y cobranza mediante intimidación. Ante cualquier urgencia existen alternativas legales: fondos de empleados, cooperativas o renegociar con el banco.", post: "como-salir-de-deudas" },
  { slug: "piramide-financiera", term: "Pirámide (esquema Ponzi)", def: "Estafa que paga 'rentabilidades' a los primeros inversionistas con la plata de los nuevos, hasta que colapsa. Señales: ganancia garantizada muy alta, presión por entrar y necesidad de reclutar más gente.", post: "como-empezar-a-invertir-en-colombia-con-poca-plata" },
  { slug: "bre-b", term: "Bre-B", def: "Sistema de pagos inmediatos del Banco de la República: transferencias entre cualquier banco o billetera del país en segundos, 24/7, usando llaves en vez de números de cuenta. Funciona desde 2025.", post: "que-es-bre-b-y-como-funciona" },
  { slug: "llave-bre-b", term: "Llave (Bre-B)", def: "Identificador que reemplaza el número de cuenta en Bre-B: tu celular, cédula, correo o un alias. Cada llave apunta a una sola cuenta y se registra en la app de tu banco o billetera.", post: "que-es-bre-b-y-como-funciona" },
  { slug: "billetera-digital", term: "Billetera digital", def: "Aplicación para guardar, enviar y recibir dinero desde el celular (Nequi, Daviplata, entre otras). Funcionan como depósitos de bajo monto, con apertura simple y sin costos de cuenta tradicional." },
  { slug: "pse", term: "PSE", def: "Botón de Pagos Seguros en Línea: sistema para pagar en comercios electrónicos debitando directamente tu cuenta bancaria. Fue el estándar del pago online en Colombia antes de la llegada de Bre-B." },
  { slug: "retencion-en-la-fuente", term: "Retención en la fuente", def: "Cobro anticipado de impuestos: quien te paga (empleador, cliente, banco) descuenta un porcentaje y lo entrega a la DIAN a tu nombre. No es un impuesto adicional — se descuenta de lo que declares al final del año.", post: "quienes-deben-declarar-renta-en-2026" },
  { slug: "declaracion-de-renta", term: "Declaración de renta", def: "Reporte anual ante la DIAN de tus ingresos, patrimonio y deducciones del año anterior. Declarar no siempre implica pagar: muchas veces las retenciones ya cubrieron el impuesto.", post: "quienes-deben-declarar-renta-en-2026" },
  { slug: "patrimonio-bruto", term: "Patrimonio bruto", def: "La suma de todo lo que posees a 31 de diciembre — cuentas, inversiones, vehículos, inmuebles — sin restar deudas. Superar 4.500 UVT te obliga a declarar renta al año siguiente.", post: "quienes-deben-declarar-renta-en-2026" },
  { slug: "salario-integral", term: "Salario integral", def: "Modalidad para salarios altos (mínimo 13 SMMLV) donde un solo pago incluye el sueldo más el factor prestacional. Quien lo recibe no cobra prima ni cesantías aparte: ya están dentro del monto.", post: "cuando-pagan-la-prima-y-como-se-calcula" },
  { slug: "liquidacion-laboral", term: "Liquidación laboral", def: "Pago final al terminar un contrato de trabajo: cesantías pendientes, intereses, prima proporcional y vacaciones no disfrutadas — más indemnización si el despido fue sin justa causa.", post: "cesantias-que-son-y-cuando-se-pagan" },
  { slug: "indemnizacion-por-despido", term: "Indemnización por despido", def: "Compensación adicional a la liquidación cuando el empleador termina el contrato sin justa causa. Su monto depende del tipo de contrato, el salario y la antigüedad del trabajador." },
  { slug: "colpensiones", term: "Colpensiones", def: "Administradora estatal del régimen de prima media: tus aportes van a un fondo común y la pensión se calcula sobre el promedio salarial de los últimos años y las semanas cotizadas." },
  { slug: "fondo-privado-de-pensiones", term: "Fondo privado de pensiones", def: "Administradora del régimen de ahorro individual: tus aportes van a una cuenta propia que se invierte y genera rendimientos. La pensión depende de cuánto acumules, no de un promedio salarial." },
  { slug: "fiado", term: "Fiado", def: "Crédito informal de confianza típico del comercio de barrio: el cliente se lleva el producto y paga después. Para el tendero es una cartera que debe controlarse con registro de cada deuda y abono.", post: "errores-financieros-mas-comunes-y-como-evitarlos" },
];

export const getTerm = (slug: string) => terms.find((t) => t.slug === slug);
